[package]
name = "memetool-ui"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
memetool_shared = { workspace = true }
shellexpand = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
yew = { workspace = true }

[workspace.dependencies]
js-sys = "0.3.59"
memetool_shared = { path = "./memetool_shared" }
serde = { version = "1.0.140", features = ["derive"] }
serde-wasm-bindgen = "0.4.3"
shellexpand = "3.0.0"

wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
web-sys = "0.3.59"
yew = { version="0.20.0", features = ["csr"] }

[workspace]
members = [
    "src-tauri",
    "memetool_shared",
]
