[package]
name = "memetool-ui"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
gloo = "0.8.0"
js-sys = { workspace = true }
memetool_shared = { workspace = true }
mime_guess = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
shellexpand = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
yew = { version="0.20.0", features = ["csr"] }
yew-hooks = "0.2.0"
yew-router = "0.17.0"

[workspace.dependencies]
base64 = "0.21.0"
image = "0.24.5"
js-sys = "0.3.59"
memetool_shared = { path = "./memetool_shared" }
mime_guess = "2.0.4"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0" }
serde-wasm-bindgen = "0.5.0"
shellexpand = "3.0.0"
tauri = { version = "1.2", features = [
    "config-json5",
    "fs-read-dir",
    "fs-read-file",
    "icon-png",
    "shell-open"
    ]}
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
web-sys = "0.3.59"

[workspace]
members = [
    "src-tauri",
    "memetool_shared",
]
